Failing tests
setup fails with
 1)
Drupal\Tests\islandora\Kernel\JsonldContextGeneratorTest::testGetContext
    LogicException: Missing bundle entity, entity type
fedora_resource_type,
    entity id rdf_source.